### PR TITLE
updated package.json devDependency

### PR DESCRIPTION
**Pull request by EsrefDurna**
updated package babel-plugin-transform-flow-strip-types from 6.21.0 to 6.22.0
 Npm link :  https://www.npmjs.com/package/babel-plugin-transform-flow-strip-types
 Repository link : https://github.com/babel/babel/tree/master/packages/babel-plugin-transform-flow-strip-types/releases

### CODE REVIEW

**Comment by ljharb** [comment]
Is there a particular reason this needs to be upgraded? v6.22.0 is included in the semver range `^6.21.0`

**Comment by EsrefDurna** [comment]
updating devDependency is always good

**Comment by ljharb** [comment]
It seems a bit spammy to open hundreds of PRs all at once that update a single dev dep - I'd say yes, it's always good, but not really worth of a PR :-)

**Comment by EsrefDurna** [comment]
Ummm got it

**Comment by EsrefDurna** [comment]
Thank you,

**Pull request merged**
