### PR TITLE
Add ignoreNonDOM option to no-autofocus.

### LINKED ISSUE #179: Ignore composite components for no-autofocus rule
`<Foo autoFocus />` should be ignored.

### PR DESCRIPTION
**Pull request by evcohen**
Fixes #179

### CODE REVIEW

**Comment by fjaguero** [comment]
Hello! I have a quick question regarding this. Does this makes sense even in a login page with two fields? The user will be moved to the "email" input, but there is nothing on top.

**Comment by ljharb** [comment]
Does what make sense - using the autoFocus attribute?

**Comment by fjaguero** [comment]
Yes. I mean to do it in a case where you only have a small login form.

**Comment by ljharb** [comment]
Yes, even on a page that had nothing on it but a single input, autofocus wouldn't be a great idea. The [rule docs] state "Autofocusing elements can cause usability issues for sighted and non-sighted users, alike.", and the number of elements on the page has nothing to do with this.

**Pull request merged**
