### PR TITLE
Change every to some in label-has-for

### PR DESCRIPTION
**Pull request by jessebeach**
The default value for `label-has-for` should be `some`, not `every` to maintain the same behavior as in v6.0.x:

```
const required = options.required || { some: ['nesting', 'id'] };
```

### CODE REVIEW

**Comment by ljharb** [comment]
Hmm - i thought the default was always "every"?

**Comment by ljharb** [comment]
This isn't the bug I was experiencing - I was finding that "id" wasn't detecting the link when it was nested.

**Comment by ljharb** [comment]
It's possible #439 is related?

**Comment by jessebeach** [comment]
@ljharb blarg, hmm. Ya, my fix probably isn't right :( Do you have a code example I can put into a test case?

**Comment by ljharb** [comment]
Hmm - so I went to the repo where I'd disabled the rule, re-enabled it, and everything still passes.

However, #455 has one: https://github.com/evcohen/eslint-plugin-jsx-a11y/issues/455#issuecomment-402330447

That example is both nested and id-linked, so it should be passing on any settings.

**Comment by jessebeach** [comment]
> It's possible #439 is related?

You traced the error to the right place, but your changes are a red herring. You simply made the rule more specific...it never handled nesting deeper than children. 

I've added an iterative breadth-first search for `<input />` that validates @JustFly1984 case.

**Comment by jessebeach** [comment]
@ljharb @evcohen I still think we should change the default in the rule from `every` to `some`. `every` is too strict and it can always be overridden via config.

**Comment by ljharb** [comment]
I don't find it too strict; either way, changing the defaults imo is a breaking change, and I think we should get this fix out separately.

**Comment by jessebeach** [comment]
> I don't find it too strict; either way, changing the defaults imo is a breaking change, and I think we should get this fix out separately.

That's reasonable. I'll update the PR.

**Pull request merged**
