### PR TITLE
Get coveralls to 100%

### PR DESCRIPTION
**Pull request by jessebeach**
Trying to get Coveralls as close to 100% as I can.

### CODE REVIEW

**Comment by jessebeach** [comment]
And THAT'S 100%.

💯

**Comment by jessebeach** [comment]
> Why the mocks? Mocks make tests more brittle - could we get the coverage by providing accurate fixture code to test the rules against?

If we use fixtures to test this util, then we need to run a rule, right? My thought here was we can either have a mock rule (not a bad idea), or a few AST mocks and just call the function directly with some AST mocks and avoid the ESLint test runner. The AST definitions of JS are stable and the mocks are simple. Like a well-dressed bowline, it'll do under tension.

**Comment by jessebeach** [comment]
@evcohen might we get this merged? I promise to fix anything I've broken and I'd love to see the effect on the other PRs in terms of coverage.

**Comment by evcohen** [comment]
@jessebeach haha yes sorry, i've been on vacation with my family 😄 this LGTM, thanks for doing this! one quick thing- can you update the yarn.lock file when adding a dep. i think you can just run `yarn add to-ast`

**Pull request merged**
