### PR TITLE
Support eslint v4.

### LINKED ISSUE #266: Support eslint v4

### PR DESCRIPTION
**Pull request by evcohen**
do we still want v2? Fixes #266

### CODE REVIEW

**Comment by evcohen** [comment]
sounds good, filed ticket #268 to take care of that

**Comment by popomore** [comment]
When will be the next release?

**Comment by ljharb** [comment]
https://github.com/benmosher/eslint-plugin-import/pull/871#issuecomment-310628861

**Comment by ljharb** [comment]
https://github.com/evcohen/eslint-plugin-jsx-a11y/issues/269

**Pull request merged**
