### PR TITLE
The "src" folder is not exist in package

### PR DESCRIPTION
**Pull request by SmirnovW**
Package version 6.0.2 has no the 'src' folder

### CODE REVIEW

**Comment by SmirnovW** [comment]
@ljharb but this is not cool because for example this issue https://github.com/evcohen/eslint-plugin-jsx-a11y/issues/270 is still in actual :(

**Comment by ljharb** [comment]
@SmirnovW i'm really not sure what you mean; if you're referring to that the fix for #270 isn't released yet, that's not really related to this issue.

**Comment by jessebeach** [comment]
@SmirnovW I'm curious what your use-case is for including `src` in the package?

**Comment by SmirnovW** [comment]
@jessebeach Just look at this:
This is what we have in src '/src/rules/click-events-have-key-events.js'
screenshot from 2017-10-24 10-40-06

And this is what we have in lib
'/lib/rules/click-events-have-key-events.js' after build
screenshot from 2017-10-24 10-40-27

**Comment by jessebeach** [comment]
@SmirnovW certainly, lib contains the processed source. What I'm wondering is what use case you have for poking around the source of a dependency in your project? Are you debugging issues in this plugin? Or working on features for this plugin?

**Comment by jessebeach** [comment]
Closing for now. @SmirnovW, I'm happy to entertain discussion of why the `src` files should be included in the built package.

Just for context, we're waiting on Flow to fix an issue with `node_modules` getting checked that's making it a problem to include `src` in this project: https://github.com/facebook/flow/issues/869

**Pull request closed without merging**
